name: CD - Snapshot

on:
  push:
    branches:
      - develop

concurrency:
  group: cd-snapshot
  cancel-in-progress: true

jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: stuart-generic-x64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: maven
      - name: Deploy snapshot
        run: mvn -B -Drepo.id=stuart-maven-snapshots -Drepo.login='${{ secrets.REPO_LOGIN }}' -Drepo.pwd='${{ secrets.REPO_PWD }}' deploy
