name: Publish to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 18, 19-ea ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Cache Maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache node
        uses: actions/cache@v2
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-
      - name: Build and publish package ${{ matrix.java-version }}
        if: matrix.java-version == "17"
        run: |
          mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false
          mvn -B -DskipTests -Pskip-shaded-web-jar -Pskip-tools-jar source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.java-version }}
        if: matrix.java-version != "17"
        run: mvn -B clean test
